USE [FINANCEIRO]
GO

/****** Object:  Table [dbo].[TB_TRANSAC_FINANC]    Script Date: 20/10/2024 09:52:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_TRANSAC_FINANC](
	[ID_TRANSACAO] [int] IDENTITY(1,1) NOT NULL,
	[IDREGISTRO] [int] NULL,
	[IDCATEGORIA] [int] NULL,
	[DATA] [date] NULL,
	[QTD_PARCELAS] [int] NULL,
	[N_PARCELA] [int] NULL,
	[VALOR_PARCELA] [decimal](12, 2) NULL,
	[VALOR_TOTAL] [decimal](12, 2) NULL,
	[DATA_VENCIMENTO_PARCELA] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_TRANSACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_TRANSAC_FINANC]  WITH CHECK ADD  CONSTRAINT [FK_IDREGISTRO_TRANSAC] FOREIGN KEY([IDREGISTRO])
REFERENCES [dbo].[TB_REG_FINANC] ([ID_REGISTRO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TB_TRANSAC_FINANC] CHECK CONSTRAINT [FK_IDREGISTRO_TRANSAC]
GO


