USE [FINANCEIRO]
GO

/****** Object:  Trigger [dbo].[TGR_ATT_TRANSACOES]    Script Date: 20/10/2024 10:01:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[TGR_ATT_TRANSACOES]
ON [dbo].[TB_REG_FINANC]
AFTER INSERT
AS

BEGIN

	DECLARE
		@CATEGORIA INT,
		@DATA_REG DATE,
		@DATA_VENCIMENTO_PARCELA DATE
		

		SELECT @CATEGORIA = IDCATEGORIA FROM INSERTED
		SELECT @DATA_REG = DATA_REGISTRO FROM INSERTED
		
		SELECT TOP 1 
			@DATA_VENCIMENTO_PARCELA = DATA_VENCIMENTO_PARCELA
		FROM 
			TB_TRANSAC_FINANC

		IF @CATEGORIA = 900 AND @DATA_REG >= @DATA_VENCIMENTO_PARCELA
		
		BEGIN
			DELETE FROM 
				TB_TRANSAC_FINANC
			WHERE 
				N_PARCELA  = QTD_PARCELAS
				

		
			UPDATE
				TB_TRANSAC_FINANC
			SET 
				N_PARCELA = N_PARCELA + 1,
				DATA_VENCIMENTO_PARCELA = DATEFROMPARTS(
				YEAR(DATEADD(MONTH, 1, DATA_VENCIMENTO_PARCELA)),
				MONTH(DATEADD(MONTH, 1, DATA_VENCIMENTO_PARCELA)),
				1
			)

			WHERE
				N_PARCELA < QTD_PARCELAS
				
		END

END
GO

ALTER TABLE [dbo].[TB_REG_FINANC] ENABLE TRIGGER [TGR_ATT_TRANSACOES]
GO


