USE [FINANCEIRO]
GO

/****** Object:  Trigger [dbo].[TGR_DELETA_REG_FINANC]    Script Date: 20/10/2024 10:02:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[TGR_DELETA_REG_FINANC]
ON [dbo].[TB_REG_FINANC]
AFTER DELETE
AS
BEGIN

	DELETE FROM TB_TRANSAC_FINANC WHERE IDREGISTRO IN (SELECT ID_REGISTRO FROM DELETED)
	DELETE FROM TB_ACOMPANHAMENTO_FINANC WHERE  IDREGISTRO IN (SELECT ID_REGISTRO FROM DELETED)
	DELETE FROM TB_APLICACAO_FINANC WHERE IDREGISTRO IN (SELECT ID_REGISTRO FROM DELETED)
END
GO

ALTER TABLE [dbo].[TB_REG_FINANC] ENABLE TRIGGER [TGR_DELETA_REG_FINANC]
GO


