USE [FINANCEIRO]
GO

/****** Object:  Table [dbo].[TB_FORMA_PAGAMENTO]    Script Date: 20/10/2024 09:51:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_FORMA_PAGAMENTO](
	[ID_FORMA] [int] NOT NULL,
	[DESCRICAO] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_FORMA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


