USE [FINANCEIRO]
GO

/****** Object:  Table [dbo].[TB_REG_FINANC]    Script Date: 20/10/2024 09:51:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_REG_FINANC](
	[ID_REGISTRO] [int] IDENTITY(10,10) NOT NULL,
	[DATA_REGISTRO] [date] NULL,
	[DATA_GASTO] [date] NULL,
	[VALOR] [decimal](12, 2) NULL,
	[DESCRICAO] [varchar](100) NULL,
	[LOCAL_GASTO] [varchar](100) NULL,
	[PARCELAMENTO] [char](1) NULL,
	[N_PARCELAS] [int] NULL,
	[IDCATEGORIA] [int] NULL,
	[IDFORMA_PAGAMENTO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_REGISTRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


