USE [FINANCEIRO]
GO

/****** Object:  Table [dbo].[TB_ACOMPANHAMENTO_FINANC]    Script Date: 20/10/2024 09:49:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_ACOMPANHAMENTO_FINANC](
	[ID] [int] IDENTITY(10,10) NOT NULL,
	[IDREGISTRO] [int] NULL,
	[DT_COMPRA] [date] NULL,
	[DT_PAGAMENTO] [date] NULL,
	[VALOR_TOTAL] [decimal](12, 2) NULL,
	[VALOR_PARCELA] [decimal](12, 2) NULL,
	[VALOR_PENDENTE] [decimal](12, 2) NULL,
	[QT_PARCELAS] [int] NULL,
	[QT_PARCELAS_PENDENTES] [int] NULL,
	[IDCATEGORIA] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_ACOMPANHAMENTO_FINANC]  WITH CHECK ADD  CONSTRAINT [FK_IDREGISTRO_ACOMPANHAMENTO] FOREIGN KEY([IDREGISTRO])
REFERENCES [dbo].[TB_REG_FINANC] ([ID_REGISTRO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TB_ACOMPANHAMENTO_FINANC] CHECK CONSTRAINT [FK_IDREGISTRO_ACOMPANHAMENTO]
GO


