SELECT * FROM TB_CATEGORIA

------QUERY VALOR EM ABERTO - MÊS ATUAL--------------
SELECT SUM(VALOR_PARCELA) FROM TB_TRANSAC_FINANC TT INNER JOIN TB_REG_FINANC TR ON TT.IDREGISTRO = TR.ID_REGISTRO WHERE month(TT.data_vencimento_parcela) = 6
	

SELECT SUM(VALOR_PARCELA) 
            FROM TB_TRANSAC_FINANC 
            WHERE MONTH(DATA_VENCIMENTO_PARCELA) = 6

	
-----------QUERY VALOR TOTAL GASTO - MÊS ATUAL---------

SELECT SUM(VALOR) FROM TB_REG_FINANC WHERE IDFORMA_PAGAMENTO != 100 AND IDCATEGORIA NOT IN (800,900) and MONTH(DATA_REGISTRO) = 5

SELECT * FROM TB_REG_FINANC WHERE IDFORMA_PAGAMENTO != 100 AND IDCATEGORIA NOT IN (800,900) and MONTH(DATA_REGISTRO) = 5

SELECT
	TC.DESCRICAO,
	SUM(VALOR_PARCELA)
FROM
	TB_CATEGORIA TC
	RIGHT JOIN TB_REG_FINANC TR
	ON TC.ID_CATEGORIA = TR.IDCATEGORIA
	LEFT JOIN TB_TRANSAC_FINANC TT
	ON TR.ID_REGISTRO = TT.IDREGISTRO

GROUP BY
	TC.DESCRICAO

----------------------------------

select sum(VALOR) from TB_REG_FINANC where IDCATEGORIA = 800


select 
	C.Descricao,
	sum(VALOR_GASTO) as 'Valor' 
from 
	TB_ACOMPANHAMENTO_FINANC AF
	JOIN TB_CATEGORIA C
	on AF.IDCATEGORIA = C.ID_CATEGORIA
where 
	AF.DT_PAGAMENTO = '2024-05-01'

GROUP BY
	C.DESCRICAO




select 
	C.ID_CATEGORIA,
	C.Descricao,
	sum(VALOR_GASTO) as 'Valor' 
from 
	TB_CATEGORIA C
	RIGHT JOIN TB_ACOMPANHAMENTO_FINANC AF
	on C.ID_CATEGORIA = AF.IDCATEGORIA
where 
	MONTH(AF.DT_PAGAMENTO) = 5
GROUP BY
	C.ID_CATEGORIA,
	C.DESCRICAO
ORDER BY
	C.DESCRICAO


	SELECT ID_CATEGORIA, DESCRICAO FROM TB_CATEGORIA



	SELECT * FROM TB_REG_FINANC WHERE IDCATEGORIA = 800