ALTER TRIGGER [TGR_INSERE_TRANSACOES]
ON [TB_REG_FINANC]
AFTER INSERT
AS

BEGIN

	DECLARE
		@IDREG INT, -- OK
		@DT DATE, --OK
		@QT_PARCELA INT, --OK
		@N_PARCELA_ATUAL INT,
		@V_PARCELA DECIMAL(12,2), --OK
		@V_TOTAL DECIMAL(12,2), --OK
		@DT_VENCIMENTO DATE, --
		@VERIFICA_COMPRA_PARCELADA CHAR(1), --OK
		@FORMA_PAGAMENTO INT,
		@CATEGORIA INT

		SELECT @FORMA_PAGAMENTO = IDFORMA_PAGAMENTO FROM INSERTED
		SELECT @VERIFICA_COMPRA_PARCELADA = PARCELAMENTO FROM INSERTED
		SELECT @CATEGORIA = IDCATEGORIA FROM inserted

		IF @VERIFICA_COMPRA_PARCELADA = 'S' OR @FORMA_PAGAMENTO = 100

		BEGIN

			SELECT @IDREG = ID_REGISTRO FROM INSERTED
			SELECT @DT = DATA_GASTO FROM INSERTED
			SELECT @QT_PARCELA = N_PARCELAS FROM INSERTED
			SELECT @V_TOTAL = VALOR FROM INSERTED
			SELECT @V_PARCELA = (@V_TOTAL / @QT_PARCELA)
			SET @DT_VENCIMENTO = DATEFROMPARTS(
				YEAR(DATEADD(MONTH, 1, @DT)),
				MONTH(DATEADD(MONTH, 1, @DT)),
				1
			)
			SET @N_PARCELA_ATUAL = 1


			INSERT INTO 
				TB_TRANSAC_FINANC (IDREGISTRO, DATA, QTD_PARCELAS, N_PARCELA, VALOR_PARCELA, VALOR_TOTAL, DATA_VENCIMENTO_PARCELA, IDCATEGORIA)
			VALUES
				(@IDREG, @DT, @QT_PARCELA, @N_PARCELA_ATUAL, @V_PARCELA, @V_TOTAL, @DT_VENCIMENTO, @CATEGORIA)
		
		END
END
