CREATE TRIGGER TGR_APLICACAO_FINANC
ON TB_REG_FINANC
AFTER INSERT
AS

BEGIN


	DECLARE
		@ID_REG INT,
		@DATA_REG DATE,
		@DESC_REG VARCHAR(100),
		@LOCAL_REG VARCHAR(100),
		@VALOR_REG DECIMAL(12,2),
		@SALDO_AT DECIMAL(12,2),
		@AGREGADOR DECIMAL(12,2)

		SELECT @ID_REG = ID_REGISTRO FROM INSERTED
		SELECT @DATA_REG = DATA_GASTO FROM INSERTED
		SELECT @DESC_REG = DESCRICAO FROM INSERTED
		SELECT @LOCAL_REG = LOCAL_GASTO FROM INSERTED
		SELECT @VALOR_REG = VALOR FROM INSERTED

		SET @SALDO_AT = (SELECT TOP 1 SALDO_ATUAL FROM TB_APLICACAO_FINANC ORDER BY DATA_APLICACAO DESC)
		SET @AGREGADOR = @SALDO_AT + @VALOR_REG

		BEGIN
			
			INSERT INTO TB_APLICACAO_FINANC(IDREGISTRO, DATA_APLICACAO, DESCRICAO, LOCAL_APLICACAO, VALOR_APLICACAO, SALDO_ATUAL)
			VALUES (@ID_REG, @DATA_REG, @DESC_REG, @LOCAL_REG, @VALOR_REG, @AGREGADOR)

		END

END